name: Firebase Web CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build_Deploy_Web:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    env:
      CI_FIREBASE_MESSAGE: ${{ github.event.head_commit.message }} - ${{ github.event.head_commit.url }}/checks

    steps:
      ## Checkout current branch
      - uses: actions/checkout@v1

      ## Setup node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      ## Install dependencies
      - name: npm install
        run: |
          npm install

      ## Build & Deploy
      - name: Build & Deploy
        run: |
          npm run-script build
          firebase deploy --only hosting --token ${{ SECRETS.CI_FIREBASE_TOKEN }} --message "$CI_FIREBASE_MESSAGE"